## Dependency reporting helpers for user-facing configure failures.

include_guard(GLOBAL)

function(_zimh_read_linux_os_release output_id output_like)
    set(_linux_id)
    set(_linux_like)

    if (DEFINED ZIMH_DEPENDENCY_HINT_LINUX_ID)
        set(_linux_id "${ZIMH_DEPENDENCY_HINT_LINUX_ID}")
    endif ()
    if (DEFINED ZIMH_DEPENDENCY_HINT_LINUX_ID_LIKE)
        set(_linux_like "${ZIMH_DEPENDENCY_HINT_LINUX_ID_LIKE}")
    endif ()

    if ((NOT _linux_id OR NOT _linux_like) AND EXISTS "/etc/os-release")
        file(STRINGS "/etc/os-release" _os_release REGEX "^(ID|ID_LIKE)=")
        foreach (_line IN LISTS _os_release)
            if (NOT _linux_id AND _line MATCHES "^ID=\"?([^\"\n]+)\"?$")
                set(_linux_id "${CMAKE_MATCH_1}")
            elseif (NOT _linux_like AND
                    _line MATCHES "^ID_LIKE=\"?([^\"\n]+)\"?$")
                set(_linux_like "${CMAKE_MATCH_1}")
            endif ()
        endforeach ()
    endif ()

    set("${output_id}" "${_linux_id}" PARENT_SCOPE)
    set("${output_like}" "${_linux_like}" PARENT_SCOPE)
endfunction()

function(_zimh_dependency_hint_platform output_variable)
    if (DEFINED ZIMH_DEPENDENCY_HINT_PLATFORM)
        set("${output_variable}" "${ZIMH_DEPENDENCY_HINT_PLATFORM}"
            PARENT_SCOPE)
        return ()
    endif ()

    if (CMAKE_SYSTEM_NAME STREQUAL "NetBSD")
        set(_platform "NetBSD")
    elseif (APPLE)
        if (EXISTS "/opt/homebrew/bin/brew" OR
            EXISTS "/usr/local/bin/brew")
            set(_platform "Homebrew")
        elseif (EXISTS "/opt/local/bin/port")
            set(_platform "MacPorts")
        else ()
            set(_platform "macOS")
        endif ()
    elseif (WIN32 AND DEFINED ENV{MSYSTEM})
        set(_platform "MSYS2")
    elseif (WIN32)
        set(_platform "MSVC")
    elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
        _zimh_read_linux_os_release(_linux_id _linux_like)
        if (_linux_id MATCHES "^(debian|ubuntu)$" OR
            _linux_like MATCHES "(^| )debian( |$)")
            set(_platform "Debian")
        elseif (_linux_id MATCHES
                "^(fedora|rhel|centos|rocky|almalinux)$" OR
                _linux_like MATCHES "(^| )(fedora|rhel)( |$)")
            set(_platform "Fedora")
        elseif (_linux_id MATCHES "^arch$" OR
                _linux_like MATCHES "(^| )arch( |$)")
            set(_platform "Arch")
        else ()
            set(_platform "Linux")
        endif ()
    else ()
        set(_platform)
    endif ()

    set("${output_variable}" "${_platform}" PARENT_SCOPE)
endfunction()

function(_zimh_dependency_package_names output_variable platform package_key)
    set(_packages)

    if (platform STREQUAL "NetBSD")
        set(_ZLIB zlib)
        set(_PCRE2 pcre2)
        set(_PNG png)
        set(_FREETYPE freetype2)
        set(_SDL2 SDL2)
        set(_SDL2_TTF SDL2_ttf)
        set(_LIBSLIRP libslirp)
        set(_CMOCKA cmocka)
        set(_VDE vde2)
    elseif (platform STREQUAL "Homebrew")
        set(_ZLIB zlib)
        set(_PCRE2 pcre2)
        set(_PNG libpng)
        set(_FREETYPE freetype)
        set(_SDL2 sdl2)
        set(_SDL2_TTF sdl2_ttf)
        set(_LIBSLIRP libslirp)
        set(_CMOCKA cmocka)
        set(_VDE vde)
    elseif (platform STREQUAL "MacPorts")
        set(_ZLIB zlib)
        set(_PCRE2 pcre2)
        set(_PNG libpng)
        set(_FREETYPE freetype)
        set(_SDL2 libsdl2)
        set(_SDL2_TTF libsdl2_ttf)
        set(_LIBSLIRP libslirp)
        set(_CMOCKA cmocka)
        set(_VDE vde2)
    elseif (platform STREQUAL "MSYS2")
        if (DEFINED ZIMH_DEPENDENCY_HINT_MSYS2_PREFIX)
            set(_prefix "${ZIMH_DEPENDENCY_HINT_MSYS2_PREFIX}")
        else ()
            set(_prefix "$ENV{MINGW_PACKAGE_PREFIX}")
        endif ()
        if (NOT _prefix)
            set(_prefix "<mingw-package-prefix>")
        endif ()

        set(_ZLIB "${_prefix}-zlib")
        set(_PCRE2 "${_prefix}-pcre2")
        set(_PNG "${_prefix}-libpng")
        set(_FREETYPE "${_prefix}-freetype")
        set(_SDL2 "${_prefix}-SDL2")
        set(_SDL2_TTF "${_prefix}-SDL2_ttf")
        set(_LIBSLIRP "${_prefix}-libslirp")
        set(_CMOCKA "${_prefix}-cmocka")
    elseif (platform STREQUAL "MSVC")
        set(_ZLIB zlib)
        set(_PCRE2 pcre2)
        set(_PNG libpng)
        set(_FREETYPE freetype)
        set(_SDL2 sdl2)
        set(_SDL2_TTF sdl2-ttf)
        set(_LIBSLIRP libslirp)
        set(_CMOCKA cmocka)
    elseif (platform STREQUAL "Debian")
        set(_ZLIB zlib1g-dev)
        set(_PCRE2 libpcre2-dev)
        set(_PNG libpng-dev)
        set(_FREETYPE libfreetype6-dev)
        set(_SDL2 libsdl2-dev)
        set(_SDL2_TTF libsdl2-ttf-dev)
        set(_LIBSLIRP libslirp-dev)
        set(_CMOCKA libcmocka-dev)
        set(_VDE libvdeplug-dev)
    elseif (platform STREQUAL "Fedora")
        set(_ZLIB zlib-devel)
        set(_PCRE2 pcre2-devel)
        set(_PNG libpng-devel)
        set(_FREETYPE freetype-devel)
        set(_SDL2 SDL2-devel)
        set(_SDL2_TTF SDL2_ttf-devel)
        set(_LIBSLIRP libslirp-devel)
        set(_CMOCKA libcmocka-devel)
        set(_VDE vde2-devel)
    elseif (platform STREQUAL "Arch")
        set(_ZLIB zlib)
        set(_PCRE2 pcre2)
        set(_PNG libpng)
        set(_FREETYPE freetype2)
        set(_SDL2 sdl2)
        set(_SDL2_TTF sdl2_ttf)
        set(_LIBSLIRP libslirp)
        set(_CMOCKA cmocka)
        set(_VDE vde2)
    endif ()

    if (DEFINED "_${package_key}")
        set(_packages "${_${package_key}}")
    endif ()

    set("${output_variable}" "${_packages}" PARENT_SCOPE)
endfunction()

function(zimh_dependency_package_hint output_variable package_key)
    _zimh_dependency_hint_platform(_platform)
    _zimh_dependency_package_names(_packages "${_platform}" "${package_key}")

    if (_packages)
        string(REPLACE ";" " " _packages "${_packages}")
    endif ()

    set(_command)
    if (_platform STREQUAL "NetBSD" AND _packages)
        set(_command "NetBSD package: pkgin install ${_packages}")
    elseif (_platform STREQUAL "Homebrew" AND _packages)
        set(_command "Homebrew package: brew install ${_packages}")
    elseif (_platform STREQUAL "MacPorts" AND _packages)
        set(_command "MacPorts package: sudo port install ${_packages}")
    elseif (_platform STREQUAL "macOS" AND _packages)
        set(_command "macOS package: use Homebrew or MacPorts: ${_packages}")
    elseif (_platform STREQUAL "MSYS2" AND _packages)
        set(_command "MSYS2 package: pacman -S ${_packages}")
    elseif (_platform STREQUAL "MSVC" AND _packages)
        set(_command "MSVC/vcpkg package: vcpkg install ${_packages}")
    elseif (_platform STREQUAL "MSVC" AND package_key STREQUAL "VDE")
        set(_command "MSVC note: VDE is not available for Windows builds")
    elseif (_platform STREQUAL "Debian" AND _packages)
        set(_command "Debian/Ubuntu package: apt install ${_packages}")
    elseif (_platform STREQUAL "Fedora" AND _packages)
        set(_command "Fedora/RHEL package: dnf install ${_packages}")
    elseif (_platform STREQUAL "Arch" AND _packages)
        set(_command "Arch package: pacman -S ${_packages}")
    endif ()

    set("${output_variable}" "${_command}" PARENT_SCOPE)
endfunction()

function(zimh_record_missing_dependency)
    set(_single_args NAME VERSION REASON PROBE DISABLE PACKAGE_KEY)
    cmake_parse_arguments(MISSING "" "${_single_args}" "" ${ARGN})

    if (NOT MISSING_NAME)
        message(FATAL_ERROR
            "zimh_record_missing_dependency requires NAME")
    endif ()

    get_property(_ids GLOBAL PROPERTY ZIMH_MISSING_DEPENDENCY_IDS)
    list(LENGTH _ids _index)
    set(_id "missing_${_index}")

    set_property(GLOBAL APPEND PROPERTY
        ZIMH_MISSING_DEPENDENCY_IDS "${_id}")
    set_property(GLOBAL PROPERTY
        "ZIMH_MISSING_DEPENDENCY_${_id}_NAME" "${MISSING_NAME}")
    set_property(GLOBAL PROPERTY
        "ZIMH_MISSING_DEPENDENCY_${_id}_VERSION" "${MISSING_VERSION}")
    set_property(GLOBAL PROPERTY
        "ZIMH_MISSING_DEPENDENCY_${_id}_REASON" "${MISSING_REASON}")
    set_property(GLOBAL PROPERTY
        "ZIMH_MISSING_DEPENDENCY_${_id}_PROBE" "${MISSING_PROBE}")
    set_property(GLOBAL PROPERTY
        "ZIMH_MISSING_DEPENDENCY_${_id}_DISABLE" "${MISSING_DISABLE}")
    set_property(GLOBAL PROPERTY
        "ZIMH_MISSING_DEPENDENCY_${_id}_PACKAGE_KEY"
        "${MISSING_PACKAGE_KEY}")
endfunction()

function(zimh_has_missing_dependencies output_variable)
    get_property(_ids GLOBAL PROPERTY ZIMH_MISSING_DEPENDENCY_IDS)
    if (_ids)
        set("${output_variable}" TRUE PARENT_SCOPE)
    else ()
        set("${output_variable}" FALSE PARENT_SCOPE)
    endif ()
endfunction()

function(zimh_format_missing_dependencies output_variable)
    get_property(_ids GLOBAL PROPERTY ZIMH_MISSING_DEPENDENCY_IDS)
    if (NOT _ids)
        set("${output_variable}" "" PARENT_SCOPE)
        return ()
    endif ()

    string(CONCAT _intro
        "ZIMH could not be configured because required dependencies are "
        "missing.")
    list(APPEND _lines "${_intro}" "" "Missing dependencies:")

    foreach (_id IN LISTS _ids)
        get_property(_name GLOBAL PROPERTY
            "ZIMH_MISSING_DEPENDENCY_${_id}_NAME")
        get_property(_version GLOBAL PROPERTY
            "ZIMH_MISSING_DEPENDENCY_${_id}_VERSION")
        get_property(_reason GLOBAL PROPERTY
            "ZIMH_MISSING_DEPENDENCY_${_id}_REASON")
        get_property(_probe GLOBAL PROPERTY
            "ZIMH_MISSING_DEPENDENCY_${_id}_PROBE")
        get_property(_disable GLOBAL PROPERTY
            "ZIMH_MISSING_DEPENDENCY_${_id}_DISABLE")
        get_property(_package_key GLOBAL PROPERTY
            "ZIMH_MISSING_DEPENDENCY_${_id}_PACKAGE_KEY")

        set(_title "${_name}")
        if (_version)
            string(APPEND _title " ${_version}")
        endif ()

        list(APPEND _lines "" "  ${_title}")
        if (_reason)
            list(APPEND _lines "    Needed because ${_reason}.")
        endif ()
        if (_probe)
            list(APPEND _lines "    CMake looked for ${_probe}.")
        endif ()

        zimh_dependency_package_hint(_package_hint "${_package_key}")
        if (_package_hint)
            list(APPEND _lines "    ${_package_hint}")
        endif ()

        if (_disable)
            list(APPEND _lines
                "    To build without this feature: cmake ${_disable} ...")
        endif ()
    endforeach ()

    string(CONCAT _retry
        "After installing packages, refresh the build directory and run "
        "CMake again.")
    list(APPEND _lines "" "${_retry}")
    string(REPLACE ";" "\n" _report "${_lines}")
    set("${output_variable}" "${_report}" PARENT_SCOPE)
endfunction()

function(zimh_report_missing_dependencies)
    zimh_format_missing_dependencies(_report)
    if (NOT _report)
        return ()
    endif ()

    message("")
    message("${_report}")
    message(FATAL_ERROR "Missing dependencies, cannot continue.")
endfunction()
