##
## Update this file as simulator directories are added, removed, or reorganized.
## Keep the top-level simulator inventory and shared simulator path variables
## here. Keep shared target-construction logic in the common CMake helpers.

## Shared simulator and source-root variables consumed by simulator-local
## CMakeLists.txt files.
set(ALPHAD     "${SIMH_SIMULATOR_ROOT}/alpha")
set(ALTAIRD    "${SIMH_SIMULATOR_ROOT}/ALTAIR")
set(ALTAIRZ80D "${SIMH_SIMULATOR_ROOT}/AltairZ80")
set(ATT3B2D    "${SIMH_SIMULATOR_ROOT}/3B2")
set(B5500D     "${SIMH_SIMULATOR_ROOT}/B5500")
set(BESM6D     "${SIMH_SIMULATOR_ROOT}/BESM6")
set(CDC1700D   "${SIMH_SIMULATOR_ROOT}/CDC1700")
set(GRID       "${SIMH_SIMULATOR_ROOT}/GRI")
set(H316D      "${SIMH_SIMULATOR_ROOT}/H316")
set(HP2100D    "${SIMH_SIMULATOR_ROOT}/HP2100")
set(HP3000D    "${SIMH_SIMULATOR_ROOT}/HP3000")
set(I1401D     "${SIMH_SIMULATOR_ROOT}/I1401")
set(I1620D     "${SIMH_SIMULATOR_ROOT}/I1620")
set(I650D      "${SIMH_SIMULATOR_ROOT}/I650")
set(I7000D     "${SIMH_SIMULATOR_ROOT}/I7000")
set(I7010D     "${SIMH_SIMULATOR_ROOT}/I7000")
set(I7094D     "${SIMH_SIMULATOR_ROOT}/I7094")
set(IBM1130D   "${SIMH_SIMULATOR_ROOT}/Ibm1130")
set(ID16D      "${SIMH_SIMULATOR_ROOT}/Interdata")
set(ID32D      "${SIMH_SIMULATOR_ROOT}/Interdata")
set(IMLACD     "${SIMH_SIMULATOR_ROOT}/imlac")
set(INTELSYSC  "${SIMH_SIMULATOR_ROOT}/Intel-Systems/common")
set(KA10D      "${SIMH_SIMULATOR_ROOT}/PDP10")
set(KI10D      "${SIMH_SIMULATOR_ROOT}/PDP10")
set(KL10D      "${SIMH_SIMULATOR_ROOT}/PDP10")
set(KS10D      "${SIMH_SIMULATOR_ROOT}/PDP10")
set(LINCD      "${SIMH_SIMULATOR_ROOT}/linc")
set(LGPD       "${SIMH_SIMULATOR_ROOT}/LGP")
set(ND100D     "${SIMH_SIMULATOR_ROOT}/ND100")
set(NOVAD      "${SIMH_SIMULATOR_ROOT}/NOVA")
set(PDP10D     "${SIMH_SIMULATOR_ROOT}/PDP10")
set(PDP11D     "${SIMH_SIMULATOR_ROOT}/PDP11")
set(PDP18BD    "${SIMH_SIMULATOR_ROOT}/PDP18B")
set(PDP1D      "${SIMH_SIMULATOR_ROOT}/PDP1")
set(PDP6D      "${SIMH_SIMULATOR_ROOT}/PDP10")
set(PDP8D      "${SIMH_SIMULATOR_ROOT}/PDP8")
set(PDQ3D      "${SIMH_SIMULATOR_ROOT}/PDQ-3")
set(S3D        "${SIMH_SIMULATOR_ROOT}/S3")
set(SAGED      "${SIMH_SIMULATOR_ROOT}/SAGE")
set(SDSD       "${SIMH_SIMULATOR_ROOT}/SDS")
set(SEL32D     "${SIMH_SIMULATOR_ROOT}/SEL32")
set(SIGMAD     "${SIMH_SIMULATOR_ROOT}/sigma")
set(SSEMD      "${SIMH_SIMULATOR_ROOT}/SSEM")
set(SWTP6800C  "${SIMH_SIMULATOR_ROOT}/swtp6800/common")
set(SWTP6800D  "${SIMH_SIMULATOR_ROOT}/swtp6800/swtp6800")
set(TT2500D    "${SIMH_SIMULATOR_ROOT}/tt2500")
set(TX0D       "${SIMH_SIMULATOR_ROOT}/TX-0")
set(UC15D      "${SIMH_SIMULATOR_ROOT}/PDP11")
set(VAXD       "${SIMH_SIMULATOR_ROOT}/VAX")

set(DISPLAYD   "${SIMH_COMPONENTS_ROOT}/display")
set(DISPLAY340 "${DISPLAYD}/type340.c")
set(DISPLAYIII "${DISPLAYD}/iii.c")
set(DISPLAYNG  "${DISPLAYD}/ng.c")
set(DISPLAYVT  "${DISPLAYD}/vt11.c")

set(INTELSYSD  "${SIMH_SIMULATOR_ROOT}/Intel-Systems")
set(INTEL_MDSD "${INTELSYSD}/Intel-MDS")
set(SCELBIC    "${INTELSYSD}/common")
set(SCELBID    "${INTELSYSD}/scelbi")

## Display sources used by simulator-local CMake metadata.
if (NOT WITH_VIDEO)
    ### Hack: Unset these variables so that they don't expand if
    ### not building with video:
    set(DISPLAY340 "")
    set(DISPLAYIII "")
    set(DISPLAYNG  "")
    set(DISPLAYVT  "")
endif ()

## Top-level simulator directory inventory.
add_subdirectory(simulators/3B2)
add_subdirectory(simulators/ALTAIR)
add_subdirectory(simulators/AltairZ80)
add_subdirectory(simulators/B5500)
add_subdirectory(simulators/BESM6)
add_subdirectory(simulators/CDC1700)
add_subdirectory(simulators/GRI)
add_subdirectory(simulators/H316)
add_subdirectory(simulators/HP2100)
add_subdirectory(simulators/HP3000)
add_subdirectory(simulators/I1401)
add_subdirectory(simulators/I1620)
add_subdirectory(simulators/I650)
add_subdirectory(simulators/I7000)
add_subdirectory(simulators/I7094)
add_subdirectory(simulators/Ibm1130)
add_subdirectory(simulators/Intel-Systems/Intel-MDS)
add_subdirectory(simulators/Intel-Systems/scelbi)
add_subdirectory(simulators/Interdata)
add_subdirectory(simulators/linc)
add_subdirectory(simulators/LGP)
add_subdirectory(simulators/ND100)
add_subdirectory(simulators/NOVA)
add_subdirectory(simulators/PDP1)
add_subdirectory(simulators/PDP10)
add_subdirectory(simulators/PDP11)
add_subdirectory(simulators/PDP18B)
add_subdirectory(simulators/PDP8)
add_subdirectory(simulators/PDQ-3)
add_subdirectory(simulators/S3)
add_subdirectory(simulators/SAGE)
add_subdirectory(simulators/SDS)
add_subdirectory(simulators/SEL32)
add_subdirectory(simulators/SSEM)
add_subdirectory(simulators/TX-0)
add_subdirectory(simulators/VAX)
add_subdirectory(simulators/alpha)
add_subdirectory(simulators/imlac)
add_subdirectory(simulators/sigma)
add_subdirectory(simulators/swtp6800/swtp6800)
add_subdirectory(simulators/tt2500)

## Top-level simulator groups that replace the old Makefile grouping targets.
## Use a simulator-specific target name here to avoid collisions with
## packaging metadata that also uses "experimental".
add_custom_target(experimental-simulators
    DEPENDS
        alpha
        pdq3
        sage)
